# Generated by Django 4.0.3 on 2022-06-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(max_length=200, verbose_name='NumProntuario')),
                ('cpf', models.CharField(blank=True, max_length=100, verbose_name='CPF')),
                ('reg_dente', models.CharField(blank=True, max_length=50, verbose_name='Região do Dente')),
                ('procedimento', models.CharField(blank=True, max_length=50, verbose_name='Procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_prontuario', models.CharField(max_length=200, verbose_name='NumProntuario')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SinaisVitaisClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pressao_arterial', models.TextField(verbose_name='Pressão Arterial')),
                ('pulso', models.TextField(verbose_name='Pulso')),
                ('respiracao', models.TextField(verbose_name='Respiração')),
                ('temperatura', models.TextField(verbose_name='Temperatura')),
                ('placa_visivel_16v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V')),
                ('placa_visivel_11v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V')),
                ('placa_visivel_26v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V')),
                ('placa_visivel_36v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V')),
                ('placa_visivel_31v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V')),
                ('placa_visivel_46v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='16V')),
                ('indice', models.CharField(max_length=5, verbose_name='Indíce')),
                ('resultado', models.CharField(choices=[('Higiene Boa', 'Higiene Boa'), ('Higiene Regular', 'Higiene regular'), ('Higiene Ruim', 'Higiene Ruim')], max_length=15, verbose_name='Resultado')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Diabetes')),
                ('gravida', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Grávida')),
                ('plan_grav', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Planeja Gravidez')),
                ('hipertensao', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Hipertensão')),
                ('sangramento', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Sangramento')),
                ('epilepsia', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Epilepsia')),
                ('prob_ren', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Problemas Renais')),
                ('doenc_mental', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Doença Mental')),
                ('rad_terapia', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Rádio Terapia')),
                ('qui_terapia', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Quimioterapia')),
                ('hepatite', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Hepatite')),
                ('articulacao', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Articulações')),
                ('protese', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Prótese')),
                ('hiv', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='HIV')),
                ('fumante', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Fumante')),
                ('herpes', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Herpes')),
                ('bebida', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], max_length=3, verbose_name='Bebida')),
                ('inf_add', models.TextField(verbose_name='Informações Adicionais')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='PsrRegPeriodSimplif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sextante_16v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Sextante 16V')),
                ('sextante_11v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Sextante 11V')),
                ('sextante_26v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Sextante 26V')),
                ('sextante_36v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Sextante 36V')),
                ('sextante_31v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Sextante 31V')),
                ('sextante_46v', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Sextante 46V')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='PSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sextante', models.CharField(blank=True, max_length=100, verbose_name='Sextante')),
                ('classificacao', models.CharField(blank=True, max_length=100, verbose_name='Classificação')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dente', models.CharField(blank=True, max_length=50, verbose_name='Região do Dente')),
                ('procedimento', models.CharField(blank=True, max_length=50, verbose_name='Procedimento')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(blank=True, max_length=100, verbose_name='Dente')),
                ('condicao', models.CharField(blank=True, max_length=100, verbose_name='Condição')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, choices=[('Med1', 'Medicamnto1'), ('Med2', 'Medicamnto2'), ('Med3', 'Medicamnto3'), ('Med4', 'Medicamnto4'), ('Med5', 'Medicamnto5')], max_length=100, verbose_name='Medicamento')),
                ('cirur_real', models.CharField(blank=True, max_length=50, verbose_name='Cirurgia Realizada')),
                ('dst', models.CharField(blank=True, max_length=50, verbose_name='DST')),
                ('anticoncepcional', models.CharField(blank=True, max_length=50, verbose_name='Anticoncepcional')),
                ('cardiopatia', models.CharField(blank=True, max_length=50, verbose_name='Cardiopatias')),
                ('prob_gastri', models.CharField(blank=True, max_length=50, verbose_name='Problemas Gastricos')),
                ('prob_pulmo', models.CharField(blank=True, max_length=50, verbose_name='Problemas Pulmonares')),
                ('alt_sang', models.CharField(blank=True, max_length=50, verbose_name='Alterações Sanguineas')),
                ('enf_ossea_infla', models.CharField(blank=True, max_length=50, verbose_name='Infermidades Osséa Inflamatorias')),
                ('habitos', models.CharField(blank=True, max_length=50, verbose_name='Hábitos')),
                ('alergias', models.CharField(blank=True, max_length=50, verbose_name='Alergias')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='InfSaudeSistemica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antecedentes_familiares', models.TextField(verbose_name='Antecedentes Familiares')),
                ('medicamentos_em_uso', models.TextField(verbose_name='Medicamentos Em uso')),
                ('cirurgias_anteriores', models.TextField(verbose_name='Cirurgias Anteriores')),
                ('problemas_cardiacos', models.TextField(verbose_name='Problemas Cardiacos')),
                ('problemas_gastrointestinais', models.TextField(verbose_name='Problemas Gastrointestinais')),
                ('alteracoes_sanguineas', models.TextField(verbose_name='Alterações Sanguineas')),
                ('enfermidades_osseas', models.TextField(verbose_name='Enfermidades Ósseas')),
                ('problemas_pulmonares', models.TextField(verbose_name='Problemas Pulmonares')),
                ('alergias', models.TextField(verbose_name='alergias')),
                ('habitos', models.TextField(verbose_name='Hábitos')),
                ('observacao', models.TextField(verbose_name='Há Alguma Informação Sobre Sua Saúde Que Não Foi Perguntada?')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExameFisicoIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm', models.CharField(blank=True, max_length=50, verbose_name='ATM')),
                ('lab_sup', models.CharField(blank=True, max_length=50, verbose_name='Labio Superior')),
                ('lab_inf', models.CharField(blank=True, max_length=50, verbose_name='LabioInferior')),
                ('com_labial', models.CharField(blank=True, max_length=50, verbose_name='Comissura Labial')),
                ('muc_jugal', models.CharField(blank=True, max_length=50, verbose_name='Mucosa Jugal')),
                ('palato_duro', models.CharField(blank=True, max_length=50, verbose_name='Palato Duro')),
                ('palato_mole', models.CharField(blank=True, max_length=50, verbose_name='Palato Mole')),
                ('tonsilas', models.CharField(blank=True, max_length=50, verbose_name='Tonsilas')),
                ('hig_oral', models.CharField(blank=True, max_length=50, verbose_name='Higiene Oral')),
                ('sang_gengival', models.CharField(blank=True, max_length=50, verbose_name='Sangramento Gengival')),
                ('calculo', models.CharField(blank=True, max_length=50, verbose_name='Cálculo')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExameFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodulos_linfaticos', models.TextField(verbose_name='Nódulos Linfáticos')),
                ('amigdalas', models.TextField(verbose_name='Amígdalas')),
                ('trigono_retromolar', models.TextField(verbose_name='Trígono Retromolar')),
                ('palato_duto', models.TextField(verbose_name='Palato Duro')),
                ('palato_mole', models.TextField(verbose_name='Palato Mole')),
                ('labios', models.TextField(verbose_name='Lábios')),
                ('pele', models.TextField(verbose_name='Pele')),
                ('atm', models.TextField(verbose_name='ATM')),
                ('vestibulo', models.TextField(verbose_name='Vestíbulo')),
                ('higiene_bucal', models.TextField(verbose_name='Higiene Bucal')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='DadosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_trat', models.CharField(blank=True, max_length=50, verbose_name='Tempo de Tratamento')),
                ('causa', models.CharField(blank=True, max_length=50, verbose_name='Causa')),
                ('crm_med', models.CharField(blank=True, max_length=50, verbose_name='CRM Medico')),
                ('tel_med', models.CharField(blank=True, max_length=25, verbose_name='Telefone Medico')),
                ('cont_urg', models.CharField(blank=True, max_length=25, verbose_name='Contato de Urgencia')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='CondOclusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_co', models.CharField(blank=True, max_length=100, verbose_name='Tipo CO')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anamnese', models.TextField(verbose_name='Anamnese')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.prontuario')),
            ],
        ),
    ]
