# Generated by Django 4.0.3 on 2022-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='prontuario',
            field=models.CharField(max_length=200, verbose_name='NumProntuario'),
        ),
    ]
