# Generated by Django 4.0.3 on 2022-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='alergias',
            field=models.TextField(blank=True, verbose_name='alergias'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='alteracoes_sanguineas',
            field=models.TextField(blank=True, verbose_name='Alterações Sanguineas'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='cirurgias_anteriores',
            field=models.TextField(blank=True, verbose_name='Cirurgias Anteriores'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='enfermidades_osseas',
            field=models.TextField(blank=True, verbose_name='Enfermidades Ósseas'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='habitos',
            field=models.TextField(blank=True, verbose_name='Hábitos'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='medicamentos_em_uso',
            field=models.TextField(blank=True, verbose_name='Medicamentos Em uso'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Há Alguma Informação Sobre Sua Saúde Que Não Foi Perguntada?'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='problemas_cardiacos',
            field=models.TextField(blank=True, verbose_name='Problemas Cardiacos'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='problemas_gastrointestinais',
            field=models.TextField(blank=True, verbose_name='Problemas Gastrointestinais'),
        ),
        migrations.AlterField(
            model_name='infsaudesistemica',
            name='problemas_pulmonares',
            field=models.TextField(blank=True, verbose_name='Problemas Pulmonares'),
        ),
    ]
