# Generated by Django 4.0.3 on 2022-03-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nome_social', models.CharField(blank=True, max_length=200, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo_biologico', models.CharField(choices=[('MASCULINO', 'masculino'), ('FEMININO', 'feminino')], max_length=9, verbose_name='Sexo Biologico')),
                ('rg', models.CharField(blank=True, max_length=16, verbose_name='RG')),
                ('cpf', models.CharField(default='86777069178', max_length=14, verbose_name='CPF')),
                ('raca', models.CharField(choices=[('BRANCO', 'branco'), ('PARDO', 'pardo'), ('PRETO', 'preto'), ('INDIGENA', 'indigena'), ('AMARELO', 'amarelo')], max_length=9, verbose_name='Raça')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('SEPARADO', 'Separado'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo')], max_length=10, verbose_name='Estado Civil')),
                ('grau_instrucao', models.CharField(choices=[('NIVEL 1', (('ANALFABETO', 'Analfabeto'), ('5º_ANO_INCOMPLETO', 'Até 5º Ano Incompleto'), ('5º_ANO_COMPLETO', 'Até 5º Ano completo'), ('6º_AO_9º_Ano_do_Fundamental', '6º ao 9º Ano do Fundamental'))), ('NIVEL 2', (('Fundamental_Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'))), ('NIVEL 3', (('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'))), ('NIVEL 4', (('Superior Completo', 'Superior Completo'),)), ('NIVEL 5', (('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')))], max_length=200, verbose_name='Grau de Instrução')),
                ('endereco', models.CharField(default='Rua Antônio Barbosa Sobrinho', max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(default='39651970', max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(default='Centro', max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Ribeirão da Folha', max_length=200, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AM', 'Amazonas'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('telefone_celular', models.CharField(default='33991514101', max_length=11, verbose_name='Telefone Celular')),
                ('antecedentes_familiares', models.TextField(default='Dados de importância para a história clínica.', verbose_name='Antecedente Familiares')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Reponsavel')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nome_social', models.CharField(blank=True, max_length=200, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo_biologico', models.CharField(choices=[('MASCULINO', 'masculino'), ('FEMININO', 'feminino')], max_length=9, verbose_name='Sexo Biologico')),
                ('rg', models.CharField(blank=True, max_length=16, verbose_name='RG')),
                ('cpf', models.CharField(default='86777069178', max_length=14, verbose_name='CPF')),
                ('raca', models.CharField(choices=[('BRANCO', 'branco'), ('PARDO', 'pardo'), ('PRETO', 'preto'), ('INDIGENA', 'indigena'), ('AMARELO', 'amarelo')], max_length=9, verbose_name='Raça')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('SEPARADO', 'Separado'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo')], max_length=10, verbose_name='Estado Civil')),
                ('grau_instrucao', models.CharField(choices=[('NIVEL 1', (('ANALFABETO', 'Analfabeto'), ('5º_ANO_INCOMPLETO', 'Até 5º Ano Incompleto'), ('5º_ANO_COMPLETO', 'Até 5º Ano completo'), ('6º_AO_9º_Ano_do_Fundamental', '6º ao 9º Ano do Fundamental'))), ('NIVEL 2', (('Fundamental_Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'))), ('NIVEL 3', (('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'))), ('NIVEL 4', (('Superior Completo', 'Superior Completo'),)), ('NIVEL 5', (('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')))], max_length=200, verbose_name='Grau de Instrução')),
                ('endereco', models.CharField(default='Rua Antônio Barbosa Sobrinho', max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(default='39651970', max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(default='Centro', max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Ribeirão da Folha', max_length=200, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AM', 'Amazonas'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('telefone_celular', models.CharField(default='33991514101', max_length=11, verbose_name='Telefone Celular')),
                ('antecedentes_familiares', models.TextField(default='Dados de importância para a história clínica.', verbose_name='Antecedente Familiares')),
            ],
            options={
                'verbose_name': 'Paciente Infantil',
                'verbose_name_plural': 'Pacientes Infantis',
            },
        ),
    ]
