# Generated by Django 4.0.3 on 2022-03-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('distribuicao', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicao',
            name='discente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.discente'),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribuicao.disciplina'),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='matricula_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.docente', verbose_name='MatDocente'),
        ),
    ]
