# Generated by Django 4.0.3 on 2022-03-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='matricula_docente',
        ),
        migrations.DeleteModel(
            name='Distribuicao',
        ),
    ]
